# Site settings
permalink: /blog/:categories/:year/:month/:day/:title.html
title: Coders Karma
email: karthik.rk18@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: karthikrk2		
github_username:  NULLPointerGuy

# Build settings
markdown: kramdown


# Setup
tagline:          'Android fanatics blog'
description:      'Hi ,I am <a href="http://NULLPointerGuy.github.io/" target="_blank">karthik</a> , i work as a  software developer in redBus. My twitter handle is <a href="https://twitter.com/karthikrk2" target="_blank">@karthikrk2</a>.'

author:
  name:           'Karthik R'
  url:            https://twitter.com/karthikrk2

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
