title: Musings about code and life
description: Musings about code and life
author: Karthik
github: https://github.com/NULLPointerGuy
about: Brewing apps, using Kotlin.
disqus_shortname: karthikrk
google_analytics: UA-47154961-3

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/karthikrk2"
    - icon: fa-github
      link: "https://github.com/NULLPointerGuy"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "http://nullpointerguy.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
